language: go
go:
  - 1.11.x
  - master
os:
  - linux
  - osx
dist: trusty
sudo: false
install: true

jobs:
  include:
    - stage: build
      script: env GO111MODULE=on go build
    - stage: test
      script: env GO111MODULE=on go test -v ./...